export const GET_USER_UPDATE = "GET_USER_UPDATE";

export const GET_PRODUCT_UPDATE = "GET_PRODUCT_UPDATE";
export const GET_PRODUCT_CATEGORY_UPDATE = "GET_PRODUCTS_CATEGORY_UPDATE";

export const GET_NOTIFY = "GET_NOTIFY";
export const GET_USER_LOGIN = "GET_USER_LOGIN";

export const GET_MODAL = "GET_MODAL";
export const GET_COUNT = "GET_COUNT";

export const GET_ATTRIBUTE = "GET_ATTRIBUTE";
export const GET_ATTRIBUTE_ID = "GET_ATTRIBUTE_ID";
export const GET_ATTRIBUTE_UPDATE = "GET_ATTRIBUTE_UPDATE";

export const GET_POST_CATEGORY_CREATE = "GET_POST_CATEGORY_CREATE";
export const GET_POST_CATEGORY_UPDATE = "GET_POST_CATEGORY_UPDATE";

export const GET_POST_CREATE = "GET_POST_CREATE";
export const GET_POST_UPDATE = "GET_POST_UPDATE";
export const SET_HOME_SLIDE = "SET_HOME_SLIDE";
export const SET_REFRESH = "SET_REFRESH";
export const SET_LOADING = "SET_LOADING";
export const SET_IS_EDIT = "SET_IS_EDIT";
